# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use Python 3.13 slim as the base image
FROM python:3.13-slim

# Install system dependencies for Playwright and browser support
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libglib2.0-0 \
        libnss3 \
        libgconf-2-4 \
        libxi6 \
        libxrender1 \
        libxrandr2 \
        libatk1.0-0 \
        libatk-bridge2.0-0 \
        libcups2 \
        libdbus-1-3 \
        libxcomposite1 \
        libxdamage1 \
        libxfixes3 \
        libxkbcommon0 \
        libgtk-3-0 \
        libpango-1.0-0 \
        libcairo2 \
        libatspi2.0-0 \
        libx11-xcb1 \
        libxcursor1 \
        libxss1 \
        libgbm1 \
        libasound2 \
        wget \
        ca-certificates \
        fonts-liberation \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy all files to the image
COPY . /app

# Remove requirements.txt to avoid installing modelcontextprotocol which is unavailable
RUN rm -f requirements.txt

# Upgrade pip
RUN pip install --upgrade pip

# Install Python dependencies using pyproject.toml dependency (mcp[cli]>=1.5.0) and playwright
RUN pip install --no-cache-dir "mcp[cli]>=1.5.0" playwright>=1.40.0

# Install Playwright browsers. Installing only chromium to reduce image size.
RUN python -m playwright install chromium

# Set the entrypoint to run the MCP server
CMD ["python3", "mcp_playwright.py"]
