[project]
name = "playwrightdebugger"
version = "0.3.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.5.0",
    "playwright>=1.40.0",
]

[project.scripts]
mcp_playwright = "mcp_playwright.main:main"